apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookcatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookcatalog
  template:
    metadata:
      labels:
        app: bookcatalog
    spec:
      containers: 
      - name: bookcatalog
        image: bookcatalog:1
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "3000"
        - name: DATABASE_URL  # Updated line
          value: "postgresql://arooma_sit722_postgresql_70e2_user:KZemH5x9yxdQsySfT5OzOv5tqcasp1Ni@dpg-crrnf2tds78s73dqks60-a.oregon-postgres.render.com/arooma_sit722_postgresql_70e2"
---
apiVersion: v1
kind: Service
metadata:
  name: bookcatalog
spec:
  selector:
    app: bookcatalog
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
